# -*- coding: utf-8 -*-
"""MNIST ANN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125cDN8997-AZUF5Vo7_zFhmSHyCLINQ7
"""

import tensorflow as tf

mnist_data=tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test)=mnist_data.load_data() #load data loads the training and test data in two tuple format

x_train,x_test=x_train/255,x_test/255 #normalize the inputs

print(x_train.shape)

#build the model
hidden_layer_size=128
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Flatten(input_shape=(28,28)),
                                  tf.keras.layers.Dense(hidden_layer_size,activation='relu'),
                                  tf.keras.layers.Dropout(0.2),
                                  tf.keras.layers.Dense(10,activation='softmax')
])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

num_of_epochs=22
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=num_of_epochs)

model.evaluate(x_test,y_test)
model.evaluate(x_train,y_train)

